default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') { 'root' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { '127.0.0.1' } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE') { 'weather_api_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE') { 'weather_api_test' } %>

production:
  <<: *default
  database: weather_api_production
  username: weather_api
  password: <%= ENV['WEATHER_API_DATABASE_PASSWORD'] %>
